// Traditional Chinese (Taiwan). Independent static catalog; no runtime character conversion.
// Matching phrases reuse translations contributed in PR #857 by @coolka-hsu (MIT).
import Foundation

enum RouterTraditionalChineseText {
  static let values: [String: String] = [
    "Uninstalling": "移除中",
    "Off by default · compacts old results; RTK shapes routed compaction": "預設關閉 · 壓縮舊結果；RTK 精簡路由壓縮輸出",
    "Fix Codex Router installation": "修復 Codex 路由安裝",
    "Language": "語言",
    "System": "跟隨系統",
    "Tray language. Reopen the panel to apply everywhere.": "系統匣語言。重新開啟面板以套用至所有位置。",
    "Usage and activity over the notch on every display": "在每個顯示器的劉海處顯示用量和活動",
    "Off by default. The menu-bar panel stays available either way.": "預設關閉。無論如何，選單欄面板始終可用。",
    "Idle": "閒置",
    "LOCAL FALLBACK": "本地回退",
    "local fallback": "本機替代",
    "%d local fallback dates": "%d 天使用本地回退",
    "1 local fallback date": "1 天使用本地回退",
    "OpenAI account usage; missing dates use local router fallback": "OpenAI 帳戶用量；缺失日期使用本地路由器回退",
    "OpenAI supplied no account bucket for these dates; local router traffic fills the gap. These are not global account totals.": "OpenAI 未提供這些日期的帳戶用量桶，已用本地路由器流量填補；這些資料不是全局帳戶總量。",
    "Thinking": "思考中",
    "Starting": "啟動中",
    "Error": "錯誤",
    "Codex subscription": "Codex 訂閱",
    "%@ left": "剩餘 %@",
    "%d chats": "%d 個工作階段",
    "Active session": "活動工作階段",
    "No traffic": "暫無流量",
    "Ready to enable": "已準備好啓用",
    "Needs setup": "需要設置",
    "OAuth · enabled": "OAuth · 已啓用",
    "API · enabled": "API · 已啓用",
    "Always": "一律顯示",
    "With Codex": "跟隨 Codex",
    "Off": "關閉",
    "Notch": "劉海區域",
    "Desktop": "桌面",
    "Usage": "用量",
    "Usage and live activity": "用量與實時活動",
    "Status": "狀態",
    "Settings": "設定",
    "Control Center": "控制中心",
    "Codex Router": "Codex Router",
    "Updated": "已更新",
    "None": "無",
    "none": "無",
    "Local": "本機",
    "Auto": "自動",
    "Codex account": "Codex 帳戶",
    "ChatGPT %@": "ChatGPT %@",
    "ChatGPT limit": "ChatGPT 限制",
    "Current usage": "目前用量",
    "All usage": "全部用量",
    "7-day snapshot": "過去 7 天快照",
    "Tokens by model": "各模型 token",
    "Router": "路由器",
    "Model speed": "模型速度",
    "Live requests": "即時請求",
    "Quota resets": "配額重置",
    "No traffic right now": "目前沒有流量",
    "Ready for the next request": "已準備好處理下一個請求",
    "No model observed": "未觀察到模型",
    "No usage recorded yet": "尚未記錄用量",
    "Waiting": "等待中",
    "No samples": "暫無樣本",
    "Appears after a metered reply": "會在計量回覆後出現",
    "Observed output throughput": "已觀測的輸出吞吐量",
    "Nothing in flight": "目前沒有進行中的請求",
    "no tools — can't chat": "沒有工具 — 無法聊天",
    "works in Codex": "在 Codex 可用",
    "unreliable in Codex": "在 Codex 中不穩定",
    "not offered yet": "暫未提供",
    "fails in Codex": "在 Codex 中失敗",
    "chat — untested": "聊天 — 未測試",
    "Provider added. Restart Codex to refresh its model picker.": "提供商已新增。請重啓 Codex 以重新整理模型選擇器。",
    "Provider hidden. Restart Codex to refresh its model picker.": "提供商已隱藏。請重啓 Codex 以重新整理模型選擇器。",
    "Show tray": "顯示托盤",
    "Appears with Codex or ChatGPT, hides when they quit": "Codex 或 ChatGPT 運行時顯示，退出後隱藏",
    "Kept on: a terminal session has no window to follow": "保持開啓：終端工作階段沒有可跟隨的視窗",
    "DeepSeek Harness": "DeepSeek Harness",
    "Install DeepSeek Harness and publish this router's models into it": "安裝 DeepSeek Harness 並將本路由的模型發佈到其中",
    "Not installed · installs the CLI, then publishes this router's models": "未安裝 · 將安裝 CLI，然後發佈本路由的模型",
    "Needs Node %@ or newer; this router runs Node %@": "需要 Node %@ 或更高版本；本路由運行的是 Node %@",
    "%@ · routed models published · `dsh web` to start": "%@ · 已發佈路由模型 · 運行 `dsh web` 啓動",
    "%@ · installed but not routed here yet": "%@ · 已安裝，但尚未接入本路由",
    "%d models published. Run `%@` to start.": "已發佈 %d 個模型。運行 `%@` 啓動。",
    "Installing DeepSeek Harness…": "正在安裝 DeepSeek Harness…",
    "Publishing routed models…": "正在發佈路由模型…",
    "Setting up DeepSeek Harness": "正在設置 DeepSeek Harness",
    "Connect": "連線",
    "Open site": "開啟網頁",
    "Turn off": "關閉",
    "Disconnect": "中斷連線",
    "Stopping…": "正在停止…",
    "Stopped. Memory and CPU released.": "已停止。記憶體和 CPU 已釋放。",
    "This harness was started outside the router — stop it where you started it.": "該 Harness 不是由本路由啓動的 — 請在啓動它的位置停止。",
    "Stop the harness process and free its memory and CPU": "停止 Harness 進程並釋放其記憶體和 CPU",
    "Disconnecting…": "正在斷開…",
    "Turned off. The harness and its own settings were kept.": "已關閉。Harness 及其自身設置已保留。",
    "Remove this router's models from the harness, keeping the harness itself": "從 Harness 中移除本路由的模型，但保留 Harness 本身",
    "Start": "啟動",
    "Open the DeepSeek Harness browser UI": "開啟 DeepSeek Harness 瀏覽器界面",
    "Start the DeepSeek Harness browser UI": "啓動 DeepSeek Harness 瀏覽器界面",
    "Starting DeepSeek Harness…": "正在啓動 DeepSeek Harness…",
    "%@ · running at %@": "%@ · 運行於 %@",
    "%@ · routed models published · not running": "%@ · 已發佈路由模型 · 未運行",
    "%d models published. Press play to open the harness.": "已發佈 %d 個模型。按播放按鈕開啟 Harness。",
    "%d models published, but the harness UI did not start: %@": "已發佈 %d 個模型，但 Harness 界面未能啓動：%@",
    "Menu bar icon stays visible": "選單欄圖標始終顯示",
    "Dynamic Island": "動態島",
    "Quotas and live activity pinned to the desktop": "將額度和實時活動固定在桌面",
    "Show provider usage and activity status": "顯示提供商用量和活動狀態",
    "Use Router with ChatGPT": "在 ChatGPT 中使用路由器",
    "Turn off 'Use Router with ChatGPT' first": "請先關閉「在 ChatGPT 中使用路由」",
    "Turn off 'Use without OpenAI login' first": "請先關閉「不使用 OpenAI 登錄」",
    "Share ChatGPT subscription": "共用 ChatGPT 訂閱",
    "Sharing status unavailable": "無法讀取共用狀態",
    "Sharing enabled": "共用已啟用",
    "Sharing disabled": "共用已停用",
    "login usable · about %@h left": "登錄可用 · 約剩 %@ 小時",
    "login usable": "登錄可用",
    "login expired": "登錄已過期",
    "login unavailable · sign-in data detected": "登錄不可用 · 檢測到登錄資料",
    "login unavailable · run codex login": "登錄不可用 · 請運行 codex login",
    "Enable ChatGPT session sharing?": "啟用 ChatGPT 工作階段共用？",
    "Enabling lets other local Codex Router clients spend this user's ChatGPT subscription. Only continue for clients you trust on this Mac.": "啓用後，其他本地 Codex Router 客戶端可以消耗此使用者的 ChatGPT 訂閱。僅對這台 Mac 上你信任的客戶端繼續。",
    "Enable sharing": "啟用共用",
    "A usable ChatGPT login is required before sharing can be enabled. Run codex login first.": "啓用共享前需要可用的 ChatGPT 登錄。請先運行 codex login。",
    "ChatGPT session-sharing status is unavailable. Refresh before changing it.": "無法讀取 ChatGPT 工作階段共享狀態。請重新整理後再更改。",
    "ChatGPT session sharing enabled for local router clients.": "已為本地路由客戶端啓用 ChatGPT 工作階段共享。",
    "ChatGPT session sharing disabled. Installed client catalogs were refreshed.": "已禁用 ChatGPT 工作階段共享，並重新整理了已安裝客戶端的目錄。",
    "Native GPT + external models · task history preserved": "原生 GPT + 外部模型 · 保留任務歷史",
    "Keep ChatGPT login and the current task history": "保留 ChatGPT 登錄和目前任務歷史",
    "Use without OpenAI login": "不登入 OpenAI 也可使用",
    "External providers · Codex restarts automatically": "外部提供商 · Codex 會自動重啓",
    "Use connected models and restart Codex": "使用已連接模型並重啓 Codex",
    "Token maxxing": "Token 精簡",
    "Cannot run subagents": "無法運行子代理",
    "Effort as subagent": "作為子代理的思考強度",
    "Forced off by CODEX_ROUTER_TOOL_RESULT_AGING=0": "已被 CODEX_ROUTER_TOOL_RESULT_AGING=0 強制關閉",
    "External models · applies on the next request": "外部模型 · 下次請求生效",
    "Providers": "供應商",
    "Auto-saved": "自動保存",
    "Applying…": "正在套用…",
    "Subagent models": "子代理模型",
    "All proven models": "所有已驗證模型",
    "Model picker": "模型挑選器",
    "Local LLMs": "本機 LLM",
    "Vision": "視覺",
    "Subagent choices do not hide models from Codex's picker — use Model picker below for that.": "子代理選擇不會隱藏 Codex 選擇器中的模型；如需隱藏模型，請使用下面的模型選擇器。",
    "Hidden models stay connected but are not offered by Codex.": "隱藏的模型仍保持連接，但不會提供給 Codex。",
    "Run models locally through Ollama. Enable an installed model to make it available to Codex.": "通過 Ollama 在本地運行模型。啓用已安裝的模型即可提供給 Codex。",
    "Run local models through Ollama or the curated MLX runtime. Installed models are wired into the same Codex proxy.": "通過 Ollama 或精選的 MLX 運行時在本地運行模型。已安裝的模型會接入同一個 Codex 代理。",
    "Nothing installed yet. Start with a quick pick or browse the Ollama catalog below.": "尚未安裝模型。請選擇快速選項，或瀏覽下面的 Ollama 目錄。",
    "Install a model": "安裝模型",
    "Install": "安裝",
    "Clear": "清除",
    "Download": "下載",
    "Cancel": "取消",
    "Confirm": "確認",
    "Confirm removal?": "確認移除？",
    "Remove model": "移除模型",
    "Measure speed": "測量速度",
    "Test image reading": "測試圖像讀取",
    "Use for image reading": "用於圖像讀取",
    "Reading images": "讀取圖像",
    "loaded": "已載入",
    "Installing local model": "安裝本機模型中",
    "Local model ready": "本機模型已就緒",
    "Local model install failed": "本機模型安裝失敗",
    "Text-only models can't see images. When on, a vision model reads the paste and hands over the text.": "純文本模型無法查看圖像。開啓後，將使用視覺模型讀取貼上內容並交給文本模型。",
    "Read images for text-only models": "為純文字模型讀取圖片",
    "Engine": "引擎",
    "Paid (cloud)": "付費（雲端）",
    "Your ChatGPT plan": "你的 ChatGPT 方案",
    "Model default": "模型預設",
    "Update": "更新",
    "Fix": "修復",
    "Working…": "處理中…",
    "Update or fix failed": "更新或修復失敗",
    "Router unavailable": "路由器無法使用",
    "Run setup, then refresh this panel.": "請先運行設置，然後重新整理此面板。",
    "Refresh": "重新整理",
    "Refreshing…": "重新整理中…",
    "%d accounts": "%d 個帳號",
    "1 account": "1 個帳號",
    "Restart": "重新啟動",
    "Restarting…": "正在重啓…",
    "Restart failed: %@": "重啓失敗：%@",
    "Restarted without updating: %@": "已重啓但未更新：%@",
    "Awaiting data": "等待資料",
    "Quit": "退出",
    "API key": "API 金鑰",
    "Replacement %@": "替換 %@",
    "Paste %@": "貼上 %@",
    "Click the check again to delete this credential": "再次點擊勾號以刪除此憑據",
    "Checking setup…": "正在檢查設置…",
    "Session expired · reconnect for account usage": "工作階段已過期 · 請重新連接以查看帳戶用量",
    "Official CLI required": "需要官方 CLI",
    "Sign in with the official CLI": "使用官方 CLI 登錄",
    "Operator-owned Google OAuth client required": "需要操作者自有的 Google OAuth 客戶端",
    "Live test required · sends a small prompt and uses quota": "需要實時測試 · 會發送一條簡短提示並消耗配額",
    "Disconnect the incompatible router record before signing in": "請先斷開不兼容的路由器憑據記錄，再登錄",
    "Setup required": "需要設置",
    "Reconnect": "重新連線",
    "Reconnect OAuth": "重新連接 OAuth",
    "Open browser sign-in": "開啟瀏覽器登錄",
    "Finish sign-in in browser": "在瀏覽器中完成登錄",
    "OAuth sessions refresh automatically. Reconnect opens browser sign-in when approval is required.": "OAuth 工作階段會自動重新整理。需要重新授權時，“重新連接”會開啟瀏覽器登錄。",
    "Install & Sign In": "安裝並登錄",
    "Sign In": "登錄",
    "Install the official CLI and sign in": "安裝官方 CLI 並登錄",
    "Sign in again with the official CLI": "使用官方 CLI 重新登錄",
    "Cancel credential replacement": "取消替換憑據",
    "Click again to delete the stored credential": "再次點擊以刪除已保存的憑據",
    "Remove stored OAuth client and session": "移除已保存的 OAuth 客戶端和工作階段",
    "Test & Enable": "測試並啓用",
    "Remove stored %@": "移除已保存的 %@",
    "Available in Codex": "可在 Codex 中使用",
    "Hidden from Codex": "已從 Codex 隱藏",
    "Signed in": "已登入",
    "Add Key": "新增密鑰",
    "Save": "保存",
    "Open usage dashboard": "開啟用量面板",
    "Daily token usage": "每日 token 用量",
    "Full": "完整",
    "Full token numbers": "完整 token 數",
    "Millions of tokens": "百萬 token",
    "Token unit": "token 單位",
    "Router traffic": "路由流量",
    "Loading provider usage…": "正在載入提供商用量…",
    "Loading native Codex usage…": "正在載入原生 Codex 用量…",
    "Set up this provider below to fetch its account usage.": "請在下方設置此提供商以獲取帳戶用量。",
    "Usage limit": "用量限制",
    "No reset reported": "未回報重設時間",
    "Reconnect below": "請在下方重新連接",
    "OAuth expired · reconnect below": "OAuth 已過期 · 請在下方重新連接",
    "No router traffic yet": "尚無路由流量",
    "Configured · currently hidden": "已設定 · 目前隱藏",
    "Sign in again to restore quota": "請重新登錄以恢復額度",
    "Local router traffic": "本地路由流量",
    "What do these tags mean?": "這些標籤是什麼意思？",
    "Hide tag guide": "隱藏標籤說明",
    "Show fewer tags": "收起標籤",
    "View all %@ tags": "查看全部 %@ 個標籤",
    "Hide machine & runtime": "隱藏設備和運行時",
    "Machine & runtime": "設備和運行時",
    "Show fewer quick picks": "顯示較少快速選項",
    "View more quick picks": "查看更多快速選項",
    "Show all": "顯示全部",
    "Hide all": "隱藏全部",
    "Update and verify Codex Router": "更新並驗證 Codex 路由",
    "Running Codex Router maintenance": "正在維護 Codex 路由",
    "Daily token usage chart. Hover a day for its displayed token count.": "每日 token 用量圖表。將滑鼠懸停在某天上可查看目前顯示的 token 數。",
    "Show %@ usage": "顯示 %@ 用量",
    "WEEKLY LEFT": "每周剩餘",
    "TODAY TOKENS": "今日 token",
    "DAILY USAGE": "每日用量",
    "LAST 7 DAYS": "過去 7 天",
    "Collapse": "收起",
    "TODAY'S TOKENS": "今日 token",
    "DAILY TOKEN TREND": "每日 token 趨勢",
    "ACTIVE NOW": "目前活動",
    "ACTIVE PROVIDER": "目前提供商",
    "USED": "已使用",
    "Account and traffic are provider-scoped": "帳戶和流量按提供商區分",
    "Live": "實時",
    "Last used": "上次使用",
    "Running chats": "執行中的對話",
    "Router overview": "路由概覽",
    "Ready": "就緒",
    "CHATGPT • NATIVE": "CHATGPT · 原生",
    "XAI • OAUTH SESSION": "XAI · OAUTH 工作階段",
    "XAI • METERED API": "XAI · 計量 API",
    "METERED API": "計量 API",
    "OAUTH ROUTE": "OAUTH 路由",
    "ChatGPT account usage": "ChatGPT 帳戶用量",
    "Measured by this router": "由此路由測量",
    "Not reported by provider": "提供商未報告",
    "Thinking · %@": "思考中 · %@",
    "ROUTER": "路由",
    "QUOTAS": "額度",
    "Connect a provider to see its quota here.": "連接提供商後可在此查看額度。",
    "DAILY TOKENS": "每日 token",
    "resets soon": "即將重置",
    "Download anyway?": "仍要下載？",
    "local model": "本機模型",
    "none installed": "未安裝任何項目",
    "installed": "已安裝",
    "ON THIS MAC": "本機",
    "MODEL": "模型",
    "SIZE": "大小",
    "QUICK PICKS": "快速選項",
    "shortlist for this Mac": "適合本機的精選",
    "CODING": "編程",
    "IMAGE READING": "圖像讀取",
    "DISCOVER OLLAMA": "發現 Ollama",
    "cloud-only": "僅雲端",
    "Size tags choose the model scale. Q4/Q8/BF16 are weight precision; MLX/NVFP4 are hardware-oriented builds; cloud tags run remotely. Codex compatibility is checked only after a pull.": "大小標籤表示模型規模。Q4/Q8/BF16 是權重精度，MLX/NVFP4 是面向硬體的構建，雲端標籤表示遠程運行。只有拉取模型後才會檢查 Codex 兼容性。",
    "Search family or tag": "搜索系列或標籤",
    "INSTALL A MODEL": "安裝模型",
    "Ollama tag or URL": "Ollama 標籤或 URL",
    "Use a tag or model-page URL. Downloads stay headless.": "輸入標籤或模型頁面 URL。下載會在後台進行。",
    "gemma4:12b or ollama.com/library/gemma4:12b": "gemma4:12b 或 ollama.com/library/gemma4:12b",
    "BEST FIT FOR THIS MAC": "最適合本機",
    "CLOUD ONLY · NO LOCAL DOWNLOAD": "僅雲端 · 不下載本地模型",
    "NO LOCAL VARIANT FITS THIS MAC": "沒有適配本機的本地變體",
    "managed": "已管理",
    "not started": "未啟動",
    "Models:": "模型：",
    "Update Ollama": "更新 Ollama",
    "cloud": "雲端",
    "won't fit": "無法適配",
    "cloud only": "僅限雲端",
    "Anyway": "仍要下載",
    "Default": "預設",
    "Cloud": "雲端",
    "Apple Silicon build": "Apple 芯片構建",
    "NVFP4 build": "NVFP4 構建",
    "4-bit build": "4 位構建",
    "8-bit build": "8 位構建",
    "BF16 build": "BF16 構建",
    "Coding build": "編程構建",
    "Specialized build": "專用構建",
    "BEST FIT": "最適合",
    "CLOUD": "雲端",
    "DEFAULT": "預設",
    "TIGHT": "記憶體緊張",
    "WON'T FIT": "無法適配",
    "memory tight": "記憶體緊張",
    "verified": "已驗證",
    "untested": "未測試",
    "accurate": "準確",
    "inaccurate": "不準確",
    "tight": "緊張",
    "too-large": "過大",
    "good": "適合",
    "tags": "標籤",
    "fit": "適配",
    "none fit": "無適配項",
    "Local model": "本機模型",
    "Installing": "安裝中",
    "testing…": "測試中…",
    "Actions for %@": "%@ 的操作",
    "speed unmeasured": "未測量速度",
    "vision only — no tools": "僅視覺 — 不支持工具",
    "Downloading": "正在下載",
    "Last download failed": "上次下載失敗",
    "ChatGPT subscription": "ChatGPT 訂閱",
    "measured on this Mac": "在本機測量",
    "tokens": "token",
    "requests": "個請求",
    "All good": "一切正常",
    "Router ready": "路由器就緒",
    "Current limit": "目前限制",
    "Daily limit": "每日限制",
    "Weekly limit": "每週限制",
    "Monthly limit": "每月限制",
    "5-hour limit": "5 小時限制",
    "Hidden from picker — show it below to use it here": "已從選擇器隱藏 — 請在下方顯示後才能使用",
    "Apply the checked-out router revision, then run the Codex doctor": "套用目前簽出的路由器版本，然後執行 Codex doctor",
    "Run the Codex doctor and repair managed router files": "運行 Codex doctor 並修復受管理的路由檔案",
    "Sign in or paste an API key": "登錄或貼上 API 密鑰",
    "required": "必填",
    "Checking…": "檢查中…",
    "Reading via": "讀取引擎",
    "Off — text-only models refuse pasted images": "關閉 — 純文本模型無法讀取貼上的圖像",
    "Daily token usage line chart": "每日 token 用量折線圖",
    "agent": "代理",
    "agents": "代理",
    "Active": "使用中",
    "Low": "低",
    "Medium": "中",
    "High": "高",
    "Model provider": "模型提供商",
    "Resets": "重置時間",
    "Menu bar mode": "選單欄模式",
    "Standard": "標準模式",
    "Icon only": "僅圖標",
    "Compact icon only, no model name text": "僅顯示緊湊圖標，隱藏模型名稱文本",
    "Show icon, model name, and usage": "顯示圖標、模型名稱及用量",
    "Show model name": "顯示模型名稱",
    "Current model or provider is visible in menu bar": "在選單欄中顯示目前模型或提供商名稱",
    "Hide model name text in menu bar": "在選單欄中隱藏模型名稱文本",
    "Menu bar icon": "選單欄圖標",
    "Router mark": "路由器標誌",
    "Provider icon": "提供商圖標",
    "Activity dot": "活動狀態點",
    "Preset icon": "預設圖標",
    "Custom image": "自定義圖片",
    "Choose the icon displayed in the menu bar": "選擇選單欄中顯示的圖標",
    "Choose Image…": "選擇圖片…",
    "No custom image selected": "未選擇自定義圖片",
    "Custom image missing": "自定義圖片已丟失",
    "Codex Router · %@ (%@) · %@": "Codex Router · %@ (%@) · %@",
    "Codex Router · %@ (%@)": "Codex Router · %@ (%@)",
    "Select": "選取",
    "Service health": "服務健康",
    "Checking": "檢查中",
    "All clear": "全部正常",
    "Serving locally": "本機服務中",
    "Degraded": "降級",
    "Offline": "離線",
    "Health endpoint unavailable": "健康狀態端點無法使用",
    "Unknown": "未知",
    "Waiting for health report": "等待健康報告",
    "Standby": "待命",
    "Not enabled": "未啟用",
    "Unreachable": "無法連線",
    "Reachable": "可連線",
    "External forwarders": "外部轉發器",
    "Subagent": "子代理",
    "thinking": "思考強度",
    "Provider catalogs": "服務商模型目錄",
    "Load the latest provider models": "載入服務商的最新模型",
    "Connect a supported provider to load its latest models.": "先連接受支持的服務商，才能載入其最新模型。",
    "Load models asks that provider for its current list. Choosing models adds them to the router and republishes every installed client.": "“載入模型”會向該服務商索取目前列表。選擇模型後會將其加入路由，並重新發佈所有已安裝的客戶端。",
    "Reload provider models": "重新載入服務商模型",
    "Reloading provider models…": "正在重新載入服務商模型…",
    "Fetch the current catalog from every connected provider that supports live model discovery.": "從每個支持實時模型發現的已連接服務商獲取目前目錄。",
    "Refresh models": "重新整理模型",
    "Reload installed and available local models from the router.": "從路由重新載入已安裝和可用的本地模型。",
    "Loading models": "載入模型",
    "Search available models": "搜索可用模型",
    "No provider models match this search.": "沒有服務商模型匹配此搜索。",
    "Search providers": "搜索提供商",
    "No providers match this search.": "沒有提供商匹配此搜索。",
    "Search subagent models": "搜索子代理模型",
    "No subagent models match this search.": "沒有子代理模型匹配此搜索。",
    "Clear search": "清除搜尋",
    "Added": "已加入",
    "Showing the first 80 matches. Search to narrow the list.": "僅顯示前 80 條匹配結果。請搜索以縮小範圍。",
    "%d selected": "已選擇 %d 個",
    "Add selected": "新增所選",
    "Load the current list from this provider.": "從該服務商載入目前列表。",
    "Run the provider's local configuration command, then refresh": "運行服務商的本地設定命令，然後重新整理",
    "saved list": "已保存列表",
    "live list": "實時列表",
    "%d models · %d added · %@": "%d 個模型 · 已新增 %d 個 · %@",
    "Router %@: %@": "路由 %@：%@",
    "%@: reload superseded by a credential change": "%@：憑據變更，重新載入已作廢",
    "Reloaded current models from 1 catalog.": "已從 1 個目錄重新載入目前模型。",
    "Reloaded current models from %d catalogs.": "已從 %d 個目錄重新載入目前模型。",
    "Catalog reload failed: %@": "目錄重新載入失敗：%@",
    "%d reloaded; %d failed: %@": "已重新載入 %d 個；%d 個失敗：%@",
    "%d %@ models loaded from %@. Select the ones to add below.": "%d 個 %@ 模型已從 %@ 載入。請在下方選擇要新增的模型。",
    "saved": "已保存",
    "current": "最新",
    "%@ is not an addable %@ catalog candidate.": "%@ 不是可新增的 %@ 目錄候選項。",
    "1 %@ model added. Restart Codex to refresh its model picker.": "已新增 1 個 %@ 模型。請重啓 Codex 以重新整理模型選擇器。",
    "%d %@ models added. Restart Codex to refresh its model picker.": "已新增 %d 個 %@ 模型。請重啓 Codex 以重新整理模型選擇器。",
    "Live compatibility verified and provider enabled. Restart Codex to refresh its model picker.": "實時兼容性已驗證並已啓用該提供商。請重啓 Codex 以重新整理模型選擇器。",
    "Opening %@ sign-in in your browser…": "正在瀏覽器中開啟 %@ 登錄…",
    "Starting %@ sign-in…": "正在啓動 %@ 登錄…",
    "Signed in. Run the live compatibility test before enabling this provider.": "已登錄。啓用該提供商前請先運行實時兼容性測試。",
    "Signed in again. Run the live compatibility test before re-enabling this provider.": "已重新登錄。重新啓用該提供商前請先運行實時兼容性測試。",
    "Provider reconnected.": "提供商已重新連接。",
    "Provider connected. Restart Codex to refresh its model picker.": "供應商已連線。重新啟動 Codex 以更新其模型挑選器。",
    "%@ saved. Restart Codex to refresh its model picker.": "%@ 已保存。請重啓 Codex 以重新整理模型選擇器。",
    "%@ removed. Restart Codex to refresh its model picker.": "%@ 已移除。請重啓 Codex 以重新整理模型選擇器。",
    "Running update and doctor…": "正在運行更新和 doctor…",
    "Update installed. Fully quit and reopen Codex to load updated models and agents.": "更新已安裝。請完全退出並重新開啟 Codex，以載入更新後的模型和代理。",
    "Running doctor --fix…": "正在運行 doctor --fix…",
    "Repair verified. Fully quit and reopen Codex if models changed.": "修復已驗證。如有模型變化，請完全退出並重新開啟 Codex。",
    "Mode changed.": "模式已更改。",
    "Codex restarted with external-provider mode.": "Codex 已以外部提供商模式重啓。",
    "Codex restarted with OpenAI login restored.": "Codex 已重啓，OpenAI 登錄已恢復。",
    "Mode changed, but Codex could not restart: %@": "模式已更改，但 Codex 無法重啓：%@",
    "Router with ChatGPT enabled. Fully quit and reopen Codex when ready.": "已啓用 ChatGPT 路由。準備好後請完全退出並重新開啟 Codex。",
    "Previous provider restored. Fully quit and reopen Codex when ready.": "已恢復之前的提供商。準備好後請完全退出並重新開啟 Codex。",
    "Model settings applied. Restart Codex to refresh its picker.": "已套用模型設定。請重新啟動 Codex 以重新整理模型選擇器。",
    "Token maxxing is on for the next external-model request.": "下一次外部模型請求已啟用 Token 精簡。",
    "Token maxxing is off; exact tool results will be sent on the next external-model request.": "Token 精簡已關閉；下一次外部模型請求將傳送精確的工具結果。",
    "%@ tested. The score is on its row.": "%@ 已測試。評分顯示在該行。",
    "%@ speed measured. Tokens per second is on its row.": "%@ 速度已測量。每秒 token 數顯示在該行。",
    "Checking the local runtime and downloader": "正在檢查本地運行時和下載器",
    "The MLX install could not start": "MLX 安裝無法啓動",
    "Qwen3.8 27B MLX is ready for Codex. Fully quit and reopen Codex to refresh its picker.": "Qwen3.8 27B MLX 已可供 Codex 使用。請完全退出並重新開啟 Codex 以重新整理模型選擇器。",
    "Qwen3.8 27B MLX installation cancelled.": "Qwen3.8 27B MLX 安裝已取消。",
    "The MLX installation failed.": "MLX 安裝失敗。",
    "Ollama updated. Its headless server will be reused for local models.": "Ollama 已更新。其後台伺服器將繼續用於本地模型。",
    "No local model operation is running.": "目前沒有進行中的本機模型操作。",
    "%@ was removed.": "%@ 已移除。",
    "%@ ready for Codex. Restart Codex to refresh its picker.": "%@ 已可供 Codex 使用。請重啓 Codex 以重新整理模型選擇器。",
    "%@ removal cancelled.": "%@ 移除已取消。",
    "%@ download cancelled.": "%@ 下載已取消。",
    "The local model removal failed.": "本地模型移除失敗。",
    "The local model download failed.": "本地模型下載失敗。",
    "%@ downloaded. Restart Codex to refresh its picker.": "%@ 已下載。請重啓 Codex 以重新整理模型選擇器。",
    "The download failed.": "下載失敗。",
    "The embedded Control Center is missing. Rebuild Codex Router.": "內置控制中心缺失。請重新構建 Codex 路由。",
    "A superseded Codex Router Control Center is still running. Quit it, then reopen Codex Router.": "仍有一個被取代的 Codex 路由控制中心在運行。請退出它，然後重新開啟 Codex 路由。",
    "Control Center could not open: %@": "控制中心無法開啟：%@",
    "the Codex desktop app could not be found": "找不到 Codex 桌面應用程式",
    "Codex did not accept a graceful quit request": "Codex 未接受正常的退出請求",
    "Codex did not quit in time; restart it manually": "Codex 未及時退出；請手動重啓",
    "This maintenance command does not schedule a desktop refresh.": "該維護命令不會安排桌面重新整理。",
    "Unsupported detached tray command.": "不支持的後台選單欄命令。",
    "Could not create the private maintenance error log.": "無法創建私有維護錯誤記錄。",
    "Codex Router control command exceeded its absolute deadline and was stopped.": "Codex 路由控制命令超出絕對時限，已被停止。",
    "Codex Router control command failed.": "Codex 路由控制命令失敗。",
    "Unsupported Codex Router script.": "不支持的 Codex 路由腳本。",
    "%@ did not answer within %d seconds and was stopped. The provider may be unreachable; try again.": "%@ 在 %d 秒內沒有響應，已被停止。提供商可能無法連接；請重試。",
    "Codex Router command failed.": "Codex 路由命令失敗。",
    "Cannot find the installed Codex Router checkout. Install the router or rebuild this app from its checkout.": "找不到已安裝的 Codex 路由檢出目錄。請安裝路由，或從檢出目錄重新構建此應用程式。",
    "This Codex Router app does not match the installed router control protocol. Install or update the router and desktop app from the same build, then reopen the app.": "此 Codex 路由應用程式與已安裝的路由控制協議不匹配。請使用同一構建安裝或更新路由和桌面應用程式，然後重新開啟應用程式。",
    "The Codex Router checkout is missing or has unsafe ownership or permissions.": "Codex 路由檢出目錄缺失，或其所有者或權限不安全。",
    "MODEL_ROUTER_PORT must be a TCP port between 1 and 65535.": "MODEL_ROUTER_PORT 必須是 1 到 65535 之間的 TCP 端口。",
    "The local router caller key is missing or invalid; run ./bin/doctor --fix.": "本地路由調用方密鑰缺失或無效；請運行 ./bin/doctor --fix。",
    "The local router health URL could not be built.": "無法構建本地路由健康檢查 URL。",
    "Choose between 1 and %d provider models.": "請選擇 1 到 %d 個提供商模型。",
    "Model id is invalid: %@": "模型 ID 無效：%@",
    "Provider model ids must be unique.": "提供商模型 ID 必須唯一。",
    "Provider is invalid: %@": "提供商無效：%@",
    "%d/%d routes enabled": "%d/%d 條路由已啓用",
    "Context savings": "上下文節省",
    "%d requests compacted all-time": "累計壓縮 %d 個請求",
    "Tool results compressed into recoverable receipts": "工具結果已壓縮為可恢復的憑據",
    "%d compacted requests in this window": "此時間視窗內壓縮了 %d 個請求",
    "No compactions in this window": "此視窗內沒有壓縮",
    "Nothing compacted in this window": "此時間視窗內沒有壓縮內容",
    "~%@ tok": "~%@ tok",
    "saved all-time": "累計節省",
    "%@ tok · %d req": "%@ token · %d 個請求",
    "%d dependency needs attention": "%d 個依賴需要處理",
    "%d dependencies need attention": "%d 個依賴需要處理",
    "Gateway": "閘道器",
    "OAuth forwarder": "OAuth 轉發器",
    "API forwarder": "API 轉發器",
    "No external forwarders enabled": "未啟用外部轉發器",
    "Every proven v2 model can run as a subagent": "所有已驗證的 v2 模型都可作為子代理運行",
    "Only selected proven v2 models can run as subagents": "只有選中的已驗證 v2 模型可作為子代理運行",
    "Subagents on": "子代理已啟用",
    "Subagents off": "子代理已停用",
    "Load models": "載入模型",
    "Reload models": "重新載入模型",
    "Removing": "正在移除",
    "Not installed": "未安裝",
    "Installation cancelled": "安裝已取消",
    "Installation failed": "安裝失敗",
    "Preparing runtime": "正在準備運行時",
    "Downloading model": "正在下載模型",
    "Loading model": "正在載入模型",
    "Starting local server": "正在啓動本地伺服器",
    "Verifying model": "驗證模型中",
    "Wiring Codex": "正在接入 Codex",
    "Ready for Codex": "已可供 Codex 使用",
    "MLX requires Apple silicon": "MLX 需要 Apple 芯片",
    "Qwen MLX ready for Codex": "Qwen MLX 已可供 Codex 使用",
    "MLX install failed": "MLX 安裝失敗",
    "Last removal failed": "上次移除失敗",
    "Removal cancelled": "移除已取消",
    "Download cancelled": "下載已取消",
    "Local model removal failed": "本機模型移除失敗",
    "Local model removal cancelled": "已取消本機模型移除",
    "Local model download cancelled": "已取消本機模型下載",
    "Local model removed": "本機模型已移除",
    "Uninstalling local model": "正在移除本機模型",
    "QWEN MLX": "QWEN MLX",
    "CODEX": "CODEX",
    "LM Studio · 4-bit · ~15 GB": "LM Studio · 4-bit · ~15 GB",
    "%@ MLX · %dK context": "%@ MLX · %dK 上下文",
    "4-bit MLX · 32K context · Apple silicon": "4-bit MLX · 32K 上下文 · Apple 芯片",
    "Apple silicon required": "需要 Apple 晶片",
    "Served only on this Mac and published to the Codex model picker.": "僅在本機提供服務，並已發佈到 Codex 模型選擇器。",
    "This MLX model is available only on Apple silicon Macs.": "此 MLX 模型僅在 Apple 芯片的 Mac 上可用。",
    "Detected: %@ · %@": "檢測到：%@ · %@",
    "LM Studio runtime": "LM Studio 運行時",
    "Model downloader": "模型下載器",
    "Reduced safety guardrails. Treat outputs as untrusted and keep the server local.": "安全防護已降低。請將輸出視為不可信，並保持伺服器僅在本地運行。",
    "Install runtime + ~15 GB model and wire Codex": "安裝運行時和約 15 GB 的模型並接入 Codex",
    "This MLX model requires an Apple silicon Mac.": "此 MLX 模型需要 Apple 芯片的 Mac。",
    "Installs official local prerequisites when missing, downloads the curated 4-bit model, and publishes it through Codex Router.": "在缺失時安裝官方本地依賴，下載精選的 4 位模型，並通過 Codex 路由發佈。",
    "The local MLX setup did not complete.": "本地 MLX 設置未完成。",
    "ready": "已就緒",
    "official installer on click": "點擊後使用官方安裝程序",
    "Source: %@": "來源：%@",
    "%d %@ · %.1f GB": "%d %@ · %.1f GB",
    "No result over 32 KB in %d requests (largest %@)": "在 %d 個請求中沒有超過 32 KB 的結果（最大 %@）",
    "Nothing aged yet in %d requests (largest %@)": "在 %d 個請求中尚無內容被壓縮（最大 %@）",
    "Saved ~%@ tokens (%@ MB) across %d requests": "節省約 %@ token（%@ MB），共 %d 個請求",
    "tokens saved · last 24 hours": "節省的 token · 最近 24 小時",
    "tokens saved · last 7 days": "節省的 token · 最近 7 天",
    "tokens saved · last 30 days": "節省的 token · 最近 30 天",
    "Cache %@ normal · %@ compacted (n=%d)": "快取命中 %@ 未壓縮 · %@ 已壓縮（n=%d）",
    "peak %@/%@": "峰值 %@/%@",
    "%@, peak %d per %@": "%@，峰值 %d，單位 %@",
    "hour": "小時",
    "day": "天",
    "%@\nIf this keeps failing, run ./bin/support-bundle and share the path.": "%@\n如果持續失敗，請運行 ./bin/support-bundle 並分享其路徑。",
    "Codex Router usage widget": "Codex Router 用量小組件",
    "%@ tokens over %d days": "%@ 個 token，覆蓋 %d 天",
    "%d percent left": "剩餘 %d%%",
    "%@, %@, %@": "%@，%@，%@",
    "%@, %@, %@, %@": "%@，%@，%@，%@",
  ]
}
