const { contextBridge, ipcRenderer } = require("electron");

const call = (name, input) => ipcRenderer.invoke(`router-control:${name}`, input);

const routerControl = Object.freeze({
  platform: process.platform,
  minimizeWindow: () => call("minimizeWindow"),
  toggleMaximizeWindow: () => call("toggleMaximizeWindow"),
  closeWindow: () => call("closeWindow"),
  getSnapshot: () => call("getSnapshot"),
  getChatGptSession: () => call("getChatGptSession"),
  getHealth: () => call("getHealth"),
  getProviders: () => call("getProviders"),
  discoverProviderModels: (providerId, options) =>
    call("discoverProviderModels", { providerId, refresh: Boolean(options?.refresh) }),
  getAccountUsage: () => call("getAccountUsage"),
  getProviderUsage: () => call("getProviderUsage"),
  getLocalModels: () => call("getLocalModels"),
  getVisionBridge: () => call("getVisionBridge"),
  getToolResultAging: () => call("getToolResultAging"),
  getDoctor: () => call("getDoctor"),
  repairInstall: () => call("repairInstall"),
  getPresence: () => call("getPresence"),
  getHarnesses: () => call("getHarnesses"),
  getContextSessions: () => call("getContextSessions"),
  refreshAll: () => call("refreshAll"),
  setProviderEnabled: (providerId, enabled) => call("setProviderEnabled", { providerId, enabled }),
  addProviderModels: (providerId, modelIds) => call("addProviderModels", { providerId, modelIds }),
  connectProvider: (providerId) => call("connectProvider", { providerId }),
  saveProviderCredential: (providerId, credential) => call("saveProviderCredential", { providerId, credential }),
  removeProviderCredential: (providerId) => call("removeProviderCredential", { providerId }),
  setSubagentMode: (mode) => call("setSubagentMode", { mode }),
  setSubagentModel: (slug, enabled) => call("setSubagentModel", { slug, enabled }),
  setSubagentEffort: (slug, effort) => call("setSubagentEffort", { slug, effort }),
  certifySubagentModels: (slugs) => call("certifySubagentModels", { slugs }),
  setSubagentSelection: (selectAll) => call("setSubagentSelection", { selectAll }),
  setPickerModel: (slug, visible) => call("setPickerModel", { slug, visible }),
  setPickerModels: (showAll) => call("setPickerModels", { showAll }),
  installLocalModel: (tag, force = false) => call("installLocalModel", { tag, force, yes: true }),
  installLocalMlx: () => call("installLocalMlx", { yes: true }),
  cancelLocalMlx: () => call("cancelLocalMlx"),
  uninstallLocalModel: (tag) => call("uninstallLocalModel", { tag }),
  setLocalModelEnabled: (tag, enabled) => call("setLocalModelEnabled", { tag, enabled }),
  benchmarkLocalModel: (tag) => call("benchmarkLocalModel", { tag }),
  controlLocalRuntime: (action) => call("controlLocalRuntime", { action }),
  setVisionBridgeEnabled: (enabled) => call("setVisionBridgeEnabled", { enabled }),
  setVisionBridgeEngine: (engine, effort) => call("setVisionBridgeEngine", { engine, effort }),
  setVisionBridgeEffort: (effort) => call("setVisionBridgeEffort", { effort }),
  downloadVisionModel: (tag) => call("downloadVisionModel", { tag }),
  useLocalVisionModel: (tag) => call("useLocalVisionModel", { tag }),
  benchmarkVisionModel: (tag) => call("benchmarkVisionModel", { tag }),
  setToolResultAging: (enabled) => call("setToolResultAging", { enabled }),
  setNativeToolResultAging: (enabled) => call("setNativeToolResultAging", { enabled }),
  setToolResultRetentionTtl: (days) => call("setToolResultRetentionTtl", { days }),
  setDefaultModel: (slug) => call("setDefaultModel", { slug }),
  setRouterDefault: (slug) => call("setRouterDefault", { slug }),
  clearRouterDefault: () => call("clearRouterDefault"),
  setSignedRouting: (enabled) => call("setSignedRouting", { enabled }),
  setChatGptSessionSharing: (enabled) => call("setChatGptSessionSharing", { enabled }),
  setPresence: (mode) => call("setPresence", { mode }),
  controlService: (action) => call("controlService", { action }),
  controlTray: (action) => call("controlTray", { action }),
  launchHarness: (harnessId, surface) => call("launchHarness", { harnessId, surface }),
  installHarness: (harnessId) => call("installHarness", { harnessId }),
  openHarnessSession: (harnessId, sessionId, surface, model) => call("openHarnessSession", { harnessId, sessionId, surface, model }),
  openExternal: (url) => call("openExternal", { url }),
  onOperation(listener) {
    if (typeof listener !== "function") throw new TypeError("Operation listener must be a function.");
    const wrapped = (_event, payload) => listener(payload);
    ipcRenderer.on("router-control:operation", wrapped);
    return () => ipcRenderer.removeListener("router-control:operation", wrapped);
  },
});

contextBridge.exposeInMainWorld("routerControl", routerControl);
